### ISSUE TITLE
Embargoes should be applied to all files attached to an object

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#372] opened 2015-07-27 17:05 UTC
In ADRL 2.0, embargoes apply to the whole work, they are not managed at the individual file level (like in worthwhile).  So, if an embargo applies to an ETD, it should cover the main ETD object, the attached PDF, and and supplemental files attached to the ETD.

**Comment by val99erie** [comment] 2015-07-31 16:17
@mark-dce Could you specify what the acceptance criteria are for this story?  Is this story covered by #388, or is there more to it than that?

**Comment by mark-dce** [comment] 2015-07-31 18:53
@val99erie #388 is mostly concerned with UI, you could still potentially obtain a link via other means.

Here's the use case:
Val is a member of the metadata administrators group.  She goes in to view an item and cut-and-pastes the link to a PDF (e.g. http://sandbox.curationexperts.com/downloads/b0%2F8b%2F6a%2F2c%2Fb08b6a2c-a375-4d6c-9042-497ded2aa0e8)  and sends it to Mark, another administrator who has rights to view the item.  Mark thinks the Thesis is really interesting, so he post the link to his blog and doesn't think about it potentially being  restricted.  Justin (a member of the general public) comes across the link on Mark's blog.  Justin should not be able to download the PDF even though he has the proper link for direct download.

It looks like this is already being enforced, but we had never explicitly discussed it, so I wrote the story to ensure this was the behavior we're implementing.

**Comment by mark-dce** [comment] 2015-07-31 18:56
@val99erie I realize that was really long - I think the acceptance criteria is
- [ ] even if I have a valid download link, it should require me to login with valid credentials and rights before I can access the file.

**Comment by acozine** [comment] 2015-08-12 16:59
Mark and I tested this behavior, we saw some irregularities before reindexing ETDs, but none after. Think the bad behavior was a result of bad data state. Cannot reproduce bad behavior. Closing.

**Closed** 2015-08-12 16:59 UTC
Labels: Access & Embargo
