### ISSUE TITLE
MARC Import Error - NoMethodError: undefined method `match' for nil:NilClass

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#355] opened 2015-07-23 15:37 UTC
Occurs on any attempted import of 004511568.xml

```
$ RAILS_ENV=production bundle exec traject -c traject_config.rb /opt/download_root/marc/004511568.xml
Performance on MRI may be improved with the concurrent-ruby-ext gem. Please see http://concurrent-ruby.com
2015-07-23T15:36:59+00:00  INFO traject (2.1.0) executing with: `-c traject_config.rb /opt/download_root/marc/004511568.xml`
2015-07-23T15:36:59+00:00  INFO Reading from /opt/download_root/marc/004511568.xml
2015-07-23T15:36:59+00:00  INFO    Indexer with 1 processing threads, reader: Traject::MarcReader and writer: ObjectFactoryWriter
2015-07-23T15:36:59+00:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<NoMethodError: undefined method `match' for nil:NilClass>
/opt/alex2/releases/20150722223719/lib/object_factory_writer.rb:88:in `block in parse_relators': undefined method `match' for nil:NilClass (NoMethodError)
	from /opt/alex2/releases/20150722223719/lib/object_factory_writer.rb:88:in `each'
	from /opt/alex2/releases/20150722223719/lib/object_factory_writer.rb:88:in `find_all'
	from /opt/alex2/releases/20150722223719/lib/object_factory_writer.rb:88:in `with_index'
	from /opt/alex2/releases/20150722223719/lib/object_factory_writer.rb:88:in `parse_relators'
	from /opt/alex2/releases/20150722223719/lib/object_factory_writer.rb:62:in `put'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:438:in `block (2 levels) in process'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/traject-2.1.0/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `call'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:62:in `block in run'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `loop'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_worker.rb:53:in `run'
	from /opt/alex2/shared/bundle/ruby/2.2.0/gems/concurrent-ruby-0.8.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:255:in `block in create_worker_thread'
```

**Comment by jcoyne** [comment] 2015-07-23 15:52
I suspect this is already fixed, but that bad data in your Solr is causing it to reoccur.

**Comment by val99erie** [comment] 2015-07-23 16:19
This might be the same as #353

**Comment by val99erie** [comment] 2015-07-24 15:47
Closing as duplicate of #353

**Closed by val99erie** 2015-07-24 15:47 UTC
Labels: bug, in-dev
