### ISSUE TITLE
ETD Importer should import expired embargo data

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#391] opened 2015-07-29 18:51 UTC
The ETD importer should import embargo data as-is (even if the date is in the past) so that the Rights Admins can view and confirm before expiring the embargo.

**Comment by val99erie** [comment] 2015-07-29 21:03
Currently I'm not able to import an ETD with an expired embargo.  The reason is because hydra-access-controls validates that the embargo release date is a future date.  It's not able to save the ETD because it's flagged as an invalid state.

https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/validators/hydra/future_date_validator.rb

Question:  Should we override that validator in Alexandria to be a no-op?  Would that cause any unexpected behavior, since the hydra-access-controls gem is expecting all embargoes to have future dates?  Or should we just close this story as "won't fix"?

Ping @jcoyne for comment.

**Comment by jcoyne** [comment] 2015-07-29 21:22
Can you call `save(validate: false)`?

**Comment by val99erie** [comment] 2015-07-30 12:27
@jcoyne I could try validate: false, but the problem is that the future date validation isn't on the Embargo object, it's on the ETD itself.

**Comment by val99erie** [comment] 2015-07-30 17:53
Per Justin's suggestion, I submitted a PR to hydra-head to create an overrideable method that allows us to disable the future date validation.

**Closed** 2015-07-31 15:37 UTC
Labels: ETD Importer, in-dev
