### ISSUE TITLE
Access & Embargo edit view missing policy labels

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#463] opened 2015-08-12 23:21 UTC
When I'm logged in as an administrator (brian) and try to view the access and embargo edit view, the policy labels are not displayed.  When I click on the select boxes, the expand with the correct number of entries, but all are blank.

EG: http://java8.curationexperts.com/etds/f3p55kmq/access/edit
<img width="831" alt="adrl2 - 463 - edit form missing policy labels" src="https://cloud.githubusercontent.com/assets/3064318/9239252/89527e7c-411f-11e5-96c2-ee079067a0fa.png">

**Comment by mark-dce** [comment] 2015-08-12 23:50
This went away after I ran the following command in the console:
```
AdminPolicy.all[1].update_index
```
So, it seems to be the same issue as #461

**Comment by jcoyne** [comment] 2015-08-13 00:29
Closing as duplicate of #461

**Closed** 2015-08-13 00:29 UTC
Labels: bug

**Comment by mark-dce** [comment] 2015-08-13 06:19
Just as a record that this was fixed but now recurs - this screen shot was taken 4-5 hours after the capture above.

<img width="845" alt="adrl2 - 463 - edit form policy labels - recurrs" src="https://cloud.githubusercontent.com/assets/3064318/9243687/5abd2bb8-4159-11e5-88ad-e2e57aceb386.png">
