### ISSUE TITLE
Fields to display in show view

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#103] opened 2015-02-25 05:43 UTC
title, alternative_title, collection title, type, creator, contributor, longitude, latitude, description, form_of_work, ark, accessionNumber, language, extent, place_of_publication, publisher, series, location, lc_subject, work_type, rights_holder, copyright_status, license, use_restrictions, institution, location_copy_sublocation

See ADRL 2.0 Metadata Model spreadsheet for additional clarification
https://docs.google.com/a/curationexperts.com/spreadsheets/d/1YnWQOKsbwfbToGYt018Q3CRXLycysUJ2S6o3j8SpvzI/edit#gid=513417340

Create a separate story for any unimplemented terms in the list above so we can close rather than blocking this ticket.

**Comment by val99erie** [comment] 2015-02-25 16:04
* [ ] title
* [ ] alternative_title
* [ ] collection title
* [ ] type
* [ ] creator
* [ ] contributor
* [ ] longitude
* [ ] latitude
* [ ] description
* [ ] form_of_work
* [ ] ark 
* [ ] accessionNumber
* [ ] language
* [ ] extent
* [ ] place_of_publication
* [ ] publisher
* [ ] series
* [ ] location
* [ ] lc_subject
* [ ] work_type
* [ ] rights_holder
* [ ] copyright_status
* [ ] license
* [ ] use_restrictions
* [ ] institution
* [ ] location_copy_sublocation

**Comment by val99erie** [comment] 2015-02-25 16:06
I'm not sure how this story is different from #86 and #87.  Is it a duplicate?

**Comment by val99erie** [comment] 2015-02-25 16:07
Oh I see, I think this story is meant to be for the Image show page, right?

**Comment by val99erie** [comment] 2015-02-25 16:09
* [ ] title
* [ ] alternative_title
* [ ] collection title
* [ ] type
* [ ] creator
* [ ] contributor
* [ ] longitude
* [ ] latitude
* [ ] description
* [ ] form_of_work
* [ ] ark 
* [ ] accessionNumber
* [ ] language
* [ ] extent
* [ ] place_of_publication
* [ ] publisher
* [ ] series
* [ ] location
* [ ] lc_subject
* [ ] work_type
* [ ] rights_holder
* [ ] copyright_status
* [ ] license
* [ ] use_restrictions
* [ ] institution
* [ ] location_copy_sublocation

**Comment by val99erie** [comment] 2015-02-25 17:09
Question:  One of the items in the list is "type".  Does that mean DC.type?  If so, that is a duplicate of "work_type".

**Comment by mark-dce** [comment] 2015-02-25 18:48
Val - my bad, all the other names are attribute names from the Metadata Model, 'type' is not.  Is was just me saying we should list the hydra object type (image, video, audio, text, etc.).  I.E. show and icon for what type of object this is.  It's moot right now since everything is an image, we can decide later if we need this once we have more object models (ETDs, videos, etc.)

**Comment by val99erie** [comment] 2015-02-25 19:34
Ok, sounds good.  For now I'll just remove 'type' from the list.

**Comment by val99erie** [comment] 2015-02-25 22:20
These are all the fields I can do for now.  The others have not yet been added to the importer.  I opened a new story for the rest of the fields, so I'll close this one.

**Closed by val99erie** 2015-02-25 22:20 UTC
